### ISSUE TITLE
support for test-unit 2.x

### ISSUE THREAD

**Issue by kares** [qrush/m#47]
is there any chance to support test-unit gem 2.x ? currently : 
```
NoMethodError: undefined method `test_suites' for Test::Unit::TestCase:Class
   suites at /opt/local/rvm/gems/jruby-1.7.21@jdbc/gems/m-1.3.4/lib/m/runners/test_unit.rb:5
   suites at /opt/local/rvm/gems/jruby-1.7.21@jdbc/gems/m-1.3.4/lib/m/executor.rb:85
    tests at /opt/local/rvm/gems/jruby-1.7.21@jdbc/gems/m-1.3.4/lib/m/executor.rb:61
  execute at /opt/local/rvm/gems/jruby-1.7.21@jdbc/gems/m-1.3.4/lib/m/executor.rb:15
      run at /opt/local/rvm/gems/jruby-1.7.21@jdbc/gems/m-1.3.4/lib/m/runner.rb:17
      run at /opt/local/rvm/gems/jruby-1.7.21@jdbc/gems/m-1.3.4/lib/m.rb:13
   (root) at /opt/local/rvm/gems/jruby-1.7.21@jdbc/gems/m-1.3.4/bin/m:4
     load at org/jruby/RubyKernel.java:1059
   (root) at /opt/local/rvm/gems/jruby-1.7.21@jdbc/bin/m:1

```
using test-unit (2.5.5)

**Comment by zamith** [comment]
To be honest I've never used `test-unit`, the gem, since most of my work is on MRI. I'll try to test it with jruby and see how hard it is to put it all together.

**Comment by zamith** [comment]
@kares Do you still have this issue? I have given it a try, but it was proving a bit to hard, and I'm not how many people really want/need support for this. What I could do is [here](https://github.com/qrush/m/tree/test-unit-experience), feel free to fiddle around and try to make it work.

Sorry for not being of more assistance.

**Comment by kares** [comment]
@zamith thanks for the inspiration ... actually got it working with test-unit 2.5 (which I need to use with JRuby 1.7) and was able to pass tests using latest test-unit gem with JRuby 9K as well ... yay!
![m](https://cloud.githubusercontent.com/assets/45967/9953390/a110b67c-5de0-11e5-81a0-5055c3c3a2ac.jpg)

**Comment by zamith** [comment]
@kares This is now in [version 1.4.0](https://github.com/qrush/m/releases/tag/v1.4.0).
